

/** TICKET */
export const CREATE_TICKET = 'CREATE_TICKET';
export const MODIFY_TICKET = 'MODIFY_TICKET';
export const CLOSE_TICKET = 'CLOSE_TICKET';
export const GET_TICKET_BY_ID = 'GET_TICKET_BY_ID';
export const GET_ALL_TICKETS = 'GET_ALL_TICKETS';
export const FETCH_DATA = 'FETCH_DATA';

/** USER */
export const REGISTER_USER = 'REGISTER_USER';
export const LOG_IN = 'LOG_IN';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';



/** FORMS */

export const SHOW_FORM = 'SHOW_FORM';
export const UPDATE_FORM  = 'UPDATE_FORM';
export const UPDATE_REGISTER_FORM = 'UPDATE_REGISTER_FORM';
export const SIGNUP_CHANGED_HANDLER = 'SIGNUP_CHANGED_HANDLER';
export const SUBMIT_TICKET = 'SUBMIT_TICKET';
export const UPDATE_TICKET_FORM = 'UPDATE_TICKET_FORM';
